(() => {
  const mn = (value, digits) => CourseNumbers.mathml(value, digits);
  const math = body => `<math>${body}</math>`;
  const value = number => math(mn(number));
  const equal = (name, number) => math(`<mrow><mi${name.length > 1 ? ' mathvariant="normal"' : ''}>${name}</mi><mo>=</mo>${mn(number)}</mrow>`);
 const root=document.querySelector('#classifier-evidence');if(!root)return;const q=s=>root.querySelector(s),rows=[[0.2,0],[0.45,1],[0.55,0],[0.9,1]];
 const node=(tag,attrs,text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n;};const sigmoid=z=>z>=0?1/(1+Math.exp(-z)):Math.exp(z)/(1+Math.exp(z));const ratio=(a,b)=>b?a/b:0;
 function draw(){const mode=q('[data-mode]').value,svg=q('svg');q('[data-probability]').hidden=mode!=='probability';q('[data-threshold-panel]').hidden=mode!=='threshold';svg.replaceChildren(node('title',{id:'evidence-title'},mode==='probability'?'Logit to probability':'Fixed scores and decision threshold'),node('desc',{id:'evidence-desc'},'Numeric values, labels and decisions are provided below this plot.'));
 if(mode==='probability'){const z=Number(q('[data-logit]').value),y=Number(q('[data-target]').value),p=sigmoid(z),l=Math.max(z,0)-z*y+Math.log1p(Math.exp(-Math.abs(z)));const sx=z=>50+(z+8)*31,sy=p=>220-180*p;const d=Array.from({length:161},(_,i)=>{const z=-8+i/10;return`${i?'L':'M'}${sx(z)},${sy(sigmoid(z))}`;}).join(' ');svg.append(node('path',{d,fill:'none',stroke:'var(--accent)','stroke-width':3}),node('circle',{cx:sx(z),cy:sy(p),r:6,fill:'currentColor'}));for(const z of[-8,-4,0,4,8])svg.append(node('text',{x:sx(z),y:248,fill:'currentColor','text-anchor':'middle'},String(z)));for(const p of[0,0.5,1])svg.append(node('text',{x:35,y:sy(p)+5,fill:'currentColor','text-anchor':'end'},String(p)));q('[data-readout]').innerHTML=`Horizontal axis: logit; vertical axis: probability. ${equal('z',z)}, target ${value(y)}, ${equal('p',p)}, probability assigned to observation ${value((y?p:1-p))}, stable ${equal('BCE',l)}.`;q('[data-rows]').innerHTML=`At threshold ${value('0.5')}, this model would predict ${value(p>=0.5?1:0)}. This decision does not change the BCE.`;
 }else{const t=Number(q('[data-threshold]').value);let tp=0,fp=0,tn=0,fn=0;const sx=p=>60+480*p;rows.forEach(([p,y],i)=>{const predicted=p>=t;if(predicted&&y)tp++;else if(predicted)fp++;else if(y)fn++;else tn++;svg.append(node('circle',{cx:sx(p),cy:45+i*45,r:7,fill:'currentColor'}),node('text',{x:sx(p)+12,y:50+i*45,fill:'currentColor'},`row${i+1}: y=${y}`));});svg.append(node('line',{x1:sx(t),x2:sx(t),y1:20,y2:205,stroke:'var(--accent)','stroke-width':3,'stroke-dasharray':'5 3'}));for(const p of[0,0.5,1])svg.append(node('text',{x:sx(p),y:245,fill:'currentColor','text-anchor':'middle'},String(p)));q('[data-readout]').innerHTML=`Horizontal axis: fixed probability; rows separate observations. Threshold ${value(t)} (positive when ${math('<mrow><mi>p</mi><mo>≥</mo><mi mathvariant="normal">threshold</mi></mrow>')}). ${equal('TP',tp)}, ${equal('FP',fp)}, ${equal('TN',tn)}, ${equal('FN',fn)}; ${equal('accuracy',ratio(tp+tn,4))}, precision ${tp+fp ? value(ratio(tp,tp+fp)) : "undefined (no predicted positives)"}, ${equal('recall',ratio(tp,tp+fn))}. When no positive decisions are made, precision is undefined; the counts remain visible.`;q('[data-rows]').innerHTML='<table><caption>Fixed probabilities; only the threshold changes</caption><thead><tr><th>Row</th><th><math><mi>p</mi></math></th><th>Target</th><th>Decision</th></tr></thead><tbody>'+rows.map(([p,y],i)=>`<tr><td>${i+1}</td><td>${value(p)}</td><td>${value(y)}</td><td>${value(p>=t?1:0)}</td></tr>`).join('')+'</tbody></table>';}}
 root.addEventListener('input',draw);q('[data-reset]').addEventListener('click',()=>{q('[data-mode]').value='probability';q('[data-logit]').value=0;q('[data-target]').value='1';q('[data-threshold]').value=0.5;draw();});draw();
})();
