const assert = require('node:assert/strict');
const {calculate} = require('./demo.js');
const balanced = calculate(0, 1, 0.02);
assert.deepEqual(balanced.attempted, [4, 4, 4]);
assert.deepEqual(balanced.accepted, [4, 4, 4]);
assert.equal(balanced.dropped, 0);
assert.ok(Math.abs(balanced.rawBalance - 1) < 1e-12);
assert.ok(Math.abs(balanced.balance - 0.02) < 1e-12);
const low = calculate(0, 0.5, 0.02);
assert.equal(low.capacity, 2);
assert.deepEqual(low.accepted, [2, 2, 2]);
assert.equal(low.dropped, 6);
assert.equal(low.rawBalance, balanced.rawBalance);
const collapsed = calculate(4, 1, 0.02);
assert.deepEqual(collapsed.attempted, [12, 0, 0]);
assert.equal(collapsed.dropped, 8);
const zero = calculate(4, 1, 0);
assert.equal(zero.balance, 0);
assert.deepEqual(zero.rows, collapsed.rows);
const tie = calculate(2, 1, 0.02);
assert.deepEqual(tie.attempted, [12, 0, 0]);
assert.ok(balanced.mean.every(value => Math.abs(value - 1 / 3) < 1e-12));
assert.ok(Math.abs(collapsed.rawBalance - 3 * collapsed.mean[0]) < 1e-12);
assert.ok(Math.abs(calculate(4, 1, 0.04).balance - 2 * collapsed.balance) < 1e-12);
console.log('chapter 48 routing illustration: all deterministic checks passed');
