bin = [
  { name = "ch01_01", path = "exercises/ch01_01.rs" },
  { name = "ch01_01_sol", path = "solutions/ch01_01.rs" },
  { name = "ch02_01", path = "exercises/ch02_01.rs" },
  { name = "ch02_01_sol", path = "solutions/ch02_01.rs" },
  { name = "ch03_01", path = "exercises/ch03_01.rs" },
  { name = "ch03_01_sol", path = "solutions/ch03_01.rs" },
  { name = "ch04_01", path = "exercises/ch04_01.rs" },
  { name = "ch04_01_sol", path = "solutions/ch04_01.rs" },
  { name = "ch05_01", path = "exercises/ch05_01.rs" },
  { name = "ch05_01_sol", path = "solutions/ch05_01.rs" },
  { name = "ch06_01", path = "exercises/ch06_01.rs" },
  { name = "ch06_01_sol", path = "solutions/ch06_01.rs" },
  { name = "ch07_01", path = "exercises/ch07_01.rs" },
  { name = "ch07_01_sol", path = "solutions/ch07_01.rs" },
  { name = "ch08_01", path = "exercises/ch08_01.rs" },
  { name = "ch08_01_sol", path = "solutions/ch08_01.rs" },
  { name = "ch09_01", path = "exercises/ch09_01.rs" },
  { name = "ch09_01_sol", path = "solutions/ch09_01.rs" },
  { name = "ch10_01", path = "exercises/ch10_01.rs" },
  { name = "ch10_01_sol", path = "solutions/ch10_01.rs" },
  { name = "ch11_01", path = "exercises/ch11_01.rs" },
  { name = "ch11_01_sol", path = "solutions/ch11_01.rs" },
  { name = "ch12_01", path = "exercises/ch12_01.rs" },
  { name = "ch12_01_sol", path = "solutions/ch12_01.rs" },
  { name = "ch13_01", path = "exercises/ch13_01.rs" },
  { name = "ch13_01_sol", path = "solutions/ch13_01.rs" },
  { name = "ch14_01", path = "exercises/ch14_01.rs" },
  { name = "ch14_01_sol", path = "solutions/ch14_01.rs" },
  { name = "ch15_01", path = "exercises/ch15_01.rs" },
  { name = "ch15_01_sol", path = "solutions/ch15_01.rs" },
  { name = "ch16_01", path = "exercises/ch16_01.rs" },
  { name = "ch16_01_sol", path = "solutions/ch16_01.rs" },
  { name = "ch17_01", path = "exercises/ch17_01.rs" },
  { name = "ch17_01_sol", path = "solutions/ch17_01.rs" },
  { name = "ch18_01", path = "exercises/ch18_01.rs" },
  { name = "ch18_01_sol", path = "solutions/ch18_01.rs" },
  { name = "ch19_01", path = "exercises/ch19_01.rs" },
  { name = "ch19_01_sol", path = "solutions/ch19_01.rs" },
  { name = "ch20_01", path = "exercises/ch20_01.rs" },
  { name = "ch20_01_sol", path = "solutions/ch20_01.rs" },
  { name = "ch21_01", path = "exercises/ch21_01.rs" },
  { name = "ch21_01_sol", path = "solutions/ch21_01.rs" },
  { name = "ch22_01", path = "exercises/ch22_01.rs" },
  { name = "ch22_01_sol", path = "solutions/ch22_01.rs" },
  { name = "ch23_01", path = "exercises/ch23_01.rs" },
  { name = "ch23_01_sol", path = "solutions/ch23_01.rs" },
  { name = "ch24_01", path = "exercises/ch24_01.rs" },
  { name = "ch24_01_sol", path = "solutions/ch24_01.rs" },
  { name = "ch25_01", path = "exercises/ch25_01.rs" },
  { name = "ch25_01_sol", path = "solutions/ch25_01.rs" },
  { name = "ch26_01", path = "exercises/ch26_01.rs" },
  { name = "ch26_01_sol", path = "solutions/ch26_01.rs" },
  { name = "ch27_01", path = "exercises/ch27_01.rs" },
  { name = "ch27_01_sol", path = "solutions/ch27_01.rs" },
  { name = "ch28_01", path = "exercises/ch28_01.rs" },
  { name = "ch28_01_sol", path = "solutions/ch28_01.rs" },
  { name = "ch29_01", path = "exercises/ch29_01.rs" },
  { name = "ch29_01_sol", path = "solutions/ch29_01.rs" },
  { name = "ch30_01", path = "exercises/ch30_01.rs" },
  { name = "ch30_01_sol", path = "solutions/ch30_01.rs" },
  { name = "ch31_01", path = "exercises/ch31_01.rs" },
  { name = "ch31_01_sol", path = "solutions/ch31_01.rs" },
  { name = "ch32_01", path = "exercises/ch32_01.rs" },
  { name = "ch32_01_sol", path = "solutions/ch32_01.rs" },
  { name = "ch33_01", path = "exercises/ch33_01.rs" },
  { name = "ch33_01_sol", path = "solutions/ch33_01.rs" },
  { name = "ch34_01", path = "exercises/ch34_01.rs" },
  { name = "ch34_01_sol", path = "solutions/ch34_01.rs" },
  { name = "ch35_01", path = "exercises/ch35_01.rs" },
  { name = "ch35_01_sol", path = "solutions/ch35_01.rs" },
  { name = "ch36_01", path = "exercises/ch36_01.rs" },
  { name = "ch36_01_sol", path = "solutions/ch36_01.rs" },
  { name = "ch37_01", path = "exercises/ch37_01.rs" },
  { name = "ch37_01_sol", path = "solutions/ch37_01.rs" },
  { name = "ch38_01", path = "exercises/ch38_01.rs" },
  { name = "ch38_01_sol", path = "solutions/ch38_01.rs" },
  { name = "ch39_01", path = "exercises/ch39_01.rs" },
  { name = "ch39_01_sol", path = "solutions/ch39_01.rs" },
  { name = "ch40_01", path = "exercises/ch40_01.rs" },
  { name = "ch40_01_sol", path = "solutions/ch40_01.rs" },
  { name = "ch41_01", path = "exercises/ch41_01.rs" },
  { name = "ch41_01_sol", path = "solutions/ch41_01.rs" },
  { name = "ch42_01", path = "exercises/ch42_01.rs" },
  { name = "ch42_01_sol", path = "solutions/ch42_01.rs" },
  { name = "ch43_01", path = "exercises/ch43_01.rs" },
  { name = "ch43_01_sol", path = "solutions/ch43_01.rs" },
  { name = "ch44_01", path = "exercises/ch44_01.rs" },
  { name = "ch44_01_sol", path = "solutions/ch44_01.rs" },
  { name = "ch45_01", path = "exercises/ch45_01.rs" },
  { name = "ch45_01_sol", path = "solutions/ch45_01.rs" },
  { name = "ch46_01", path = "exercises/ch46_01.rs" },
  { name = "ch46_01_sol", path = "solutions/ch46_01.rs" },
  { name = "ch47_01", path = "exercises/ch47_01.rs" },
  { name = "ch47_01_sol", path = "solutions/ch47_01.rs" },
  { name = "ch48_01", path = "exercises/ch48_01.rs" },
  { name = "ch48_01_sol", path = "solutions/ch48_01.rs" },
  { name = "ch49_01", path = "exercises/ch49_01.rs" },
  { name = "ch49_01_sol", path = "solutions/ch49_01.rs" },
  { name = "ch50_01", path = "exercises/ch50_01.rs" },
  { name = "ch50_01_sol", path = "solutions/ch50_01.rs" },
  { name = "ch51_01", path = "exercises/ch51_01.rs" },
  { name = "ch51_01_sol", path = "solutions/ch51_01.rs" },
  { name = "ch52_01", path = "exercises/ch52_01.rs" },
  { name = "ch52_01_sol", path = "solutions/ch52_01.rs" },
  { name = "ch53_01", path = "exercises/ch53_01.rs" },
  { name = "ch53_01_sol", path = "solutions/ch53_01.rs" },
  { name = "ch54_01", path = "exercises/ch54_01.rs" },
  { name = "ch54_01_sol", path = "solutions/ch54_01.rs" },
  { name = "ch55_01", path = "exercises/ch55_01.rs" },
  { name = "ch55_01_sol", path = "solutions/ch55_01.rs" },
  { name = "ch56_01", path = "exercises/ch56_01.rs" },
  { name = "ch56_01_sol", path = "solutions/ch56_01.rs" },
]

[package]
name = "first_principles_exercises"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false
[workspace]
